export const SP = 'SP'
export const NAME = `bi-${SP}-name`
export const SAVEPREFIX = 'Pa_'
const AR = `bi-${SP}-ar`

export const data = {
  "bd-z": "2",
  "bd-width": "10px",
  "bd-color": "#3748E7",
  "bd-bg-color": "#000",
  "hm-width": "34px",
  "hm-hight": "0px",
  "hm-radius": "50px",
  "hm-bg-color": "#F287CF",
  "sb-z": "1",
  "sb-opacity": "1",
  "sb-height": "26px",
  "sb-top": "10px",
  "sb-offset-x": "0px",
  "sb-blur": "0px",
  "sb-radius": "0px",
  "sb-bg-color": "radial-gradient(circle at 50% 50%, #000 0%, rgb(0 0 0 / 55%) 60%)",
  "sc-opacity": "1",
  "sc-size": "64px",
  "sc-bottom": "186px",
  "sc-offset-x": "56px",
  "sc-blur": "4px",
  "sc-bg-color": "rgb(255 255 255 / .3)",
  "fp-opacity": "1",
  "fp-size": "84px",
  "fp-bottom": "176px",
  "fp-offset-x": "158px",
  "fp-blur": "0px",
  "fp-bg-color": "#9BA4FF",
  "bg-opacity": "1",
  "bg-height": "637px",
  "bg-top": "10px",
  "bg-offset-x": "9px",
  "bg-blur": "0px",
  "bg-radius": "0px",
  "bg-color": "#aaa",
  "cd-opacity": "1",
  "cd-height": "267px",
  "cd-top": "614px",
  "cd-offset-x": "10px",
  "cd-blur": "0px",
  "cd-radius": "24px",
  "cd-bg-color": "#2d1887",
  [NAME]: "",
  [AR]: "84/187",
  "bi-width": "400px",
  "bi-hole-size": "25.7px",
  "bi-hole-top": "9.6px",
  "bi-radius": "34px",
  "bi-wallpaper-scale": "1.1",
  "bi-lockscreen-drim": "0.8"
}